% This function computes the magnetic flux density and the magnetic moment
% generated by a square spire in which a current I is flowing. 
function [Btot,m] = B_1_square_spire(Square_Normal, Square_Centre,...
                                     Square_Dimension, P, I)
% Square_Normal: 1 --> x, 2 --> y, 3 --> z
if(Square_Normal == 1)
 [Bx By Bz] = [B_1_wire(2,Square_Centre - [0 0 Square_Dimension(3)/2],...
               Square_Dimension(2), P, I)];
 Btot = [Bx By Bz];
 [Bx By Bz] = [B_1_wire(3,Square_Centre + [0 Square_Dimension(2)/2 0],...
               Square_Dimension(3), P, I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(2,Square_Centre + [0 0 Square_Dimension(3)/2],...
               Square_Dimension(2), P, -I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(3,Square_Centre - [0 Square_Dimension(2)/2 0],...
               Square_Dimension(3), P, -I)];
 Btot = Btot + [Bx By Bz];
 m = Square_Dimension(2)*Square_Dimension(3)*I;
 
elseif(Square_Normal == 2)
 [Bx By Bz] = [B_1_wire(3,Square_Centre - [Square_Dimension(1)/2 0 0],...
               Square_Dimension(3), P, I)];
 Btot = [Bx By Bz];
 [Bx By Bz] = [B_1_wire(1,Square_Centre + [0 0 Square_Dimension(3)/2],...
               Square_Dimension(1), P, I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(3,Square_Centre + [Square_Dimension(1)/2 0 0],...
               Square_Dimension(3), P, -I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(1,Square_Centre - [0 0 Square_Dimension(3)/2],...
               Square_Dimension(1), P, -I)];
 Btot = Btot + [Bx By Bz];
 m = Square_Dimension(1)*Square_Dimension(3)*I;
 
 elseif(Square_Normal == 3)
 [Bx By Bz] = [B_1_wire(1,Square_Centre - [0 Square_Dimension(2)/2 0],...
               Square_Dimension(1), P, I)];
 Btot = [Bx By Bz];
 [Bx By Bz] = [B_1_wire(2,Square_Centre + [Square_Dimension(1)/2 0 0],...
               Square_Dimension(2), P, I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(1,Square_Centre + [0 Square_Dimension(2)/2 0],...
               Square_Dimension(1), P, -I)];
 Btot = Btot + [Bx By Bz];
 [Bx By Bz] = [B_1_wire(2,Square_Centre - [Square_Dimension(1)/2 0 0],...
               Square_Dimension(2), P, -I)];
 Btot = Btot + [Bx By Bz];
 m = Square_Dimension(1)*Square_Dimension(2)*I;
 
 
 mu0 = 4*pi*0.0000001;
 % Formule du Durand pour B le long de l'axe d'une spire carrée, juste pour 
% Vérification --> Ok!
%  a = Square_Dimension(1);
%  b = abs(Square_Centre(3) - P(3));
%  Bz_Durand = ((2*sqrt(2))/(pi) * ((mu0*I*a*a)/((a^2 + 4*b^2)*sqrt(a^2+2*b^2))))
end
end