% This function computes the magnetic flux density generated by a wire of 
% finite lentth at the point P. 
function [Bx By Bz] = B_1_wire(Wire_Direction,Wire_Centre,Wire_Length,P,I)
mu0 = 4*pi*0.0000001;
% Wire_Direction : 1 --> x, 2 --> y, 3 --> z
if(Wire_Direction == 1)
    alpha = sqrt((P(3)-Wire_Centre(3))^2 + (P(2) - Wire_Centre(2))^2);
    u1 = atan((P(1)-(Wire_Centre(1) - Wire_Length/2))/(alpha));
    u2 = atan((P(1)-(Wire_Centre(1) + Wire_Length/2))/(alpha));
    Bx = 0;
    By = (mu0*I/(4*pi*alpha^2))*(P(3) - Wire_Centre(3))*(sin(u2) - sin(u1));
    Bz = -(mu0*I/(4*pi*alpha^2))*(P(2) - Wire_Centre(2))*(sin(u2) - sin(u1));
elseif(Wire_Direction == 2)
    alpha = sqrt((P(1)-Wire_Centre(1))^2 + (P(3) - Wire_Centre(3))^2);
    u1 = atan((P(2)-(Wire_Centre(2) - Wire_Length/2))/(alpha));
    u2 = atan((P(2)-(Wire_Centre(2) + Wire_Length/2))/(alpha));
    Bx = -(mu0*I/(4*pi*alpha^2))*(P(3) - Wire_Centre(3))*(sin(u2) - sin(u1));
    By = 0;
%     Other version of the same thing
%     t1 = (sign((P(2)-(Wire_Centre(2) - Wire_Length/2))))/(sqrt(1+((alpha*alpha)/((P(2)-(Wire_Centre(2) - Wire_Length/2))^2))));
%     t2 = (sign((P(2)-(Wire_Centre(2) + Wire_Length/2))))/(sqrt(1+((alpha*alpha)/((P(2)-(Wire_Centre(2) + Wire_Length/2))^2))));
%     
%     Bz = -(mu0*I/(4*pi*alpha^2))*(P(1) - Wire_Centre(1))*(t1-t2);
    Bz = (mu0*I/(4*pi*alpha^2))*(P(1) - Wire_Centre(1))*(sin(u2) - sin(u1));
elseif(Wire_Direction == 3)
    alpha = sqrt((P(1)-Wire_Centre(1))^2 + (P(2) - Wire_Centre(2))^2);
    u1 = atan((P(3)-(Wire_Centre(3) - Wire_Length/2))/(alpha));
    u2 = atan((P(3)-(Wire_Centre(3) + Wire_Length/2))/(alpha));
    Bx = (mu0*I/(4*pi*alpha^2))*(P(2) - Wire_Centre(2))*(sin(u2) - sin(u1));
    By = -(mu0*I/(4*pi*alpha^2))*(P(1) - Wire_Centre(1))*(sin(u2) - sin(u1));
    Bz = 0;
end
end