%% This function computes the magnetic flux density generated by a cuboidal
%% superconductor. Jc vary linearly between GoodJc at the top surface and 
%% BadJc at the bottom surface.
function [Btot,mtot] = B_1cuboid_Superconductor_JcVaryAlongCaxis(Caxis,...
                       Bulk_Centre, Bulk_Dimension, P, Nb_Slice,...
                       Nb_Spire,JcVary_sign,GoodJc,BadJc)
Surface_Dimension = Bulk_Dimension;
Surface_Dimension(abs(Caxis)) = 0;
Surface_Centre = Bulk_Centre;
Btot = [0 0 0];
mtot = 0;
JcNominal = (GoodJc + BadJc)/2;
KcNominal = JcNominal * ((Bulk_Dimension(abs(Caxis)))/(Nb_Slice));
temp(1) = Btot(3);
Kc_Variation = (GoodJc - BadJc)* ((Bulk_Dimension(abs(Caxis)))/(Nb_Slice));
BadFaceDeficit = Kc_Variation/2;
for i = 1 : Nb_Slice
    Surface_Centre(abs(Caxis)) = Bulk_Centre(abs(Caxis))-...
                                ((Bulk_Dimension(abs(Caxis)))/(2))+...
                                ((Bulk_Dimension(abs(Caxis)))/(2*Nb_Slice))+...
                                (i-1)*((Bulk_Dimension(abs(Caxis)))/(Nb_Slice));
    if(JcVary_sign>0)
        Kc = KcNominal -BadFaceDeficit + i*((Kc_Variation)/(Nb_Slice));
    else
        Kc = KcNominal -BadFaceDeficit + (Kc_Variation) - i*((Kc_Variation)/(Nb_Slice));
    end
    [Btemp,mtemp] = B_1Supercond_Surface(abs(Caxis), Surface_Centre, Surface_Dimension, P, Kc, Nb_Spire);
    Btot = Btot + Btemp;
    mtot = mtot + mtemp;
    temp(i+1) = Btot(3);
end

% DEBUG : Just to observe the impact of each slice on the total field
% plot(0:Nb_Slice,temp)
end
