%% This function computes the magnetic flux density generated by a cuboidal
%% superconductor. Jc is assumed homoegeneous, isotropic and field independent.
function [Btot] = B_1cuboid_Superconductor(Caxis, Bulk_Centre, Bulk_Dimension, P, Jc, Nb_Slice, Nb_Spire)
Surface_Dimension = Bulk_Dimension;
Surface_Dimension(abs(Caxis)) = 0;
Surface_Centre = Bulk_Centre;
Kc = Jc * ((Bulk_Dimension(abs(Caxis)))/(Nb_Slice));
Btot = [0 0 0];
temp(1) = Btot(3);
for i = 1 : Nb_Slice
    Surface_Centre(abs(Caxis)) = Bulk_Centre(abs(Caxis)) - ((Bulk_Dimension(abs(Caxis)))/(2)) + ((Bulk_Dimension(abs(Caxis)))/(2*Nb_Slice)) + (i-1)*((Bulk_Dimension(abs(Caxis)))/(Nb_Slice));
    Btot = Btot + B_1Supercond_Surface(abs(Caxis), Surface_Centre, Surface_Dimension, P, Kc, Nb_Spire);
    temp(i+1) = Btot(3);
end

% Just to observe the impact of each slice on the total field
% plot(0:Nb_Slice,temp)
end
s