%% This function computes the magnetic flux density generated by a cuboidal
%% superconductor. Jc vary linearly between GoodJc at the top surface and 
%% BadJc at the bottom surface. The model also take into account a anistropic
%% Jc (only implemented for caxis= 1 for now).
function [Btot,mtot] = B_1cuboid_Superconductor_JcAnysotropicAndVaryAlongCaxis(Caxis, Bulk_Centre, Bulk_Dimension, P, Nb_Slice, Nb_Spire,JcVary_sign,GoodJc,BadJc,AnisotropyFactor)
Surface_Dimension = Bulk_Dimension;
Surface_Dimension(Caxis) = 0;
Surface_Centre = Bulk_Centre;
Btot = [0 0 0];
mtot = 0;
JcNominal = (GoodJc + BadJc)/2;
KcNominal = JcNominal * ((Bulk_Dimension(Caxis))/(Nb_Slice));
temp(1) = Btot(3);
Kc_Variation = (GoodJc - BadJc)* ((Bulk_Dimension(Caxis))/(Nb_Slice));
BadFaceDeficit = Kc_Variation/2;
for i = 1 : Nb_Slice
    Surface_Centre(Caxis) = Bulk_Centre(Caxis) - ((Bulk_Dimension(Caxis))/(2)) + ((Bulk_Dimension(Caxis))/(2*Nb_Slice)) + (i-1)*((Bulk_Dimension(Caxis))/(Nb_Slice));
    if(JcVary_sign>0)
        Kc = KcNominal -BadFaceDeficit + i*((Kc_Variation)/(Nb_Slice));
    else
        Kc = KcNominal -BadFaceDeficit + (Kc_Variation) - i*((Kc_Variation)/(Nb_Slice));
    end
    [Btemp,mtemp] = B_1Supercond_Surface_JcAnysotropic(Caxis, Surface_Centre, Surface_Dimension, P, Kc, Nb_Spire,AnisotropyFactor);
    Btot = Btot + Btemp;
    mtot = mtot + mtemp;
    temp(i+1) = Btot(3);
end

% Just to observe the impact of each slice on the total field
% plot(0:Nb_Slice,temp)
end
