%% This function computes the magnetic flux density generated by a truncated 
%% cube superconductor.
function [Btot] = B_1HalfCube_Superconductor(Caxis,ChangingDim,Cube_Base,...
                                             Cube_Dimension,P,Jc,Nb_Slice,...
                                             Nb_Spire)
Kc = Jc * ((Cube_Dimension(abs(Caxis)))/(Nb_Slice));
Btot = [0 0 0];
Surface_Centre = Cube_Base;
for i = 1 : Nb_Slice
   Surface_Centre(abs(Caxis)) = Cube_Base(abs(Caxis))+i*sign(Caxis)*...
                                (Cube_Dimension(abs(Caxis))/(Nb_Slice+1));
   Surface_Centre(abs(ChangingDim)) = Cube_Base(abs(ChangingDim))+...
                                      sign(ChangingDim)*i*...
                                      (Cube_Dimension(abs(ChangingDim))/(2*(Nb_Slice+1)));
   Surface_Dimensiontemp = Cube_Dimension;
   Surface_Dimensiontemp(abs(ChangingDim)) = Cube_Dimension(abs(ChangingDim))*...
                                             (1- (i/(Nb_Slice+1)));
   Surface_Dimensiontemp(abs(Caxis)) = 0;
   Btot = Btot + B_1Supercond_Surface(abs(Caxis), Surface_Centre,...
                                      Surface_Dimensiontemp, P, Kc,...
                                      Nb_Spire);  
   
   %% DEBUG Verify the created shape
%    x1 = Surface_Centre(1) - Surface_Dimensiontemp(1)/2;
%    x2 = Surface_Centre(1) + Surface_Dimensiontemp(1)/2;
%    
%    y1 = Surface_Centre(2) - Surface_Dimensiontemp(2)/2;
%    y2 = Surface_Centre(2) + Surface_Dimensiontemp(2)/2;
%    
%    z1 = Surface_Centre(3) - Surface_Dimensiontemp(3)/2;
%    z2 = Surface_Centre(3) + Surface_Dimensiontemp(3)/2; 
%    
%    
%    plot3([x1 x2],[y1 y1],[z1 z2],'b')
%    hold on;
%    plot3([x1 x2],[y2 y2],[z1 z2],'b')
%    plot3([x1 x1],[y1 y2],[z1 z2],'b')
%    plot3([x2 x2],[y1 y2],[z1 z2],'b')
%    
%    plot3([x1 x2],[y1 y2],[z1 z1],'b')
%    plot3([x1 x2],[y1 y2],[z2 z2],'b')
%    plot3([x1 x1],[y1 y2],[z1 z2],'b')
%    plot3([x2 x2],[y1 y2],[z1 z2],'b')
%    
%    plot3([x1 x2],[y1 y2],[z1 z1],'b')
%    plot3([x1 x2],[y1 y2],[z2 z2],'b')
%    plot3([x1 x2],[y1 y1],[z1 z2],'b')
%    plot3([x1 x2],[y2 y2],[z1 z2],'b')
%    xlabel('x')
%    ylabel('y')
%    zlabel('z')
end
end