%% This function computes the magnetic flux density generated by a pyramidal superconductor
% Care, the pyramid can only point toward positive x,y or z. (Could be updated later)
function [Btot] = B_1Pyramid_Superconductor(Caxis,Pyramid_Base,...
                                            Pyramid_Dimension,P,Jc,...
                                            Nb_Slice,Nb_Spire,...
                                            Flagonlyonedir)
Kc = Jc * ((Pyramid_Dimension(Caxis))/(Nb_Slice));
Btot = [0 0 0];
Surface_Centre = Pyramid_Base;
for i = 1 : Nb_Slice
   Surface_Centre(Caxis) = Pyramid_Base(Caxis)+...
                           i*(Pyramid_Dimension(Caxis)/(Nb_Slice+1));
   Surface_Dimensiontemp = Pyramid_Dimension*(1- (i/(Nb_Slice+1)));  
   if(Flagonlyonedir==1)
       Surface_Dimensiontemp(1) = Pyramid_Dimension(1);
   elseif(Flagonlyonedir==2)
       Surface_Dimensiontemp(2) = Pyramid_Dimension(2);
   end
   Surface_Dimensiontemp(Caxis) = 0;
   Btot = Btot + B_1Supercond_Surface(Caxis, Surface_Centre,...
                                      Surface_Dimensiontemp, P, Kc,...
                                      Nb_Spire);   
end
end