% This function computes the magnetic flux density generated by a fully 
% penetrated superconducting plate at point P. The calculation is performed by
% subdiving the plates into Nb_Spire square current loops in which a 
% current Kc*(Smaller_dimension/2*Nb_spire)is flowing.
function [Btot,mtot] = B_1Supercond_Surface(Caxis, Surface_Centre, ...
                       Surface_Dimension, P, Kc, Nb_Spire)
% Caxis: 1 --> x, 2 --> y, 3 --> z
if(Caxis == 1)
    if(Surface_Dimension(2)<Surface_Dimension(3))
        Smaller_Dim = Surface_Dimension(2);
    else
        Smaller_Dim = Surface_Dimension(3);
    end  
elseif(Caxis == 2)
    if(Surface_Dimension(1)<Surface_Dimension(3))
        Smaller_Dim = Surface_Dimension(1);
    else
        Smaller_Dim = Surface_Dimension(3);
    end
elseif(Caxis == 3)
    if(Surface_Dimension(1)<Surface_Dimension(2))
        Smaller_Dim = Surface_Dimension(1);
    else
        Smaller_Dim = Surface_Dimension(2);
    end
end

Btot = [0 0 0];
mtot =0;
for(i = 1:Nb_Spire)
   Spire_Dimension = [Surface_Dimension(1)-i*(Smaller_Dim/(Nb_Spire))+...
                     ((Smaller_Dim/(Nb_Spire))/2) Surface_Dimension(2)-...
                     i*(Smaller_Dim/(Nb_Spire))+((Smaller_Dim/(Nb_Spire))/2)... 
                      Surface_Dimension(3)-i*(Smaller_Dim/(Nb_Spire))+...
                      ((Smaller_Dim/(Nb_Spire))/2)];
   Spire_Dimension(Caxis) = 0;
   [Btemp mtemp] = B_1_square_spire(Caxis, Surface_Centre,...
                                    Spire_Dimension, P,...
                                    Kc*((Smaller_Dim)/(2*Nb_Spire)));
   Btot = Btot + Btemp;
   mtot = mtot + mtemp;   
end

end