%% This function computes the field generated by a trapezoidal superconductor 

% Care, the trapezoid can only point toward positive x,y or z. (Could be updated later)
function [Btot] = B_1Trapezoid_Superconductor(Caxis,Pyramid_Base,...
                                              Pyramid_Dimension,height,P,...
                                              Jc,Nb_Slice,Nb_Spire,...
                                              Flagonlyonedir)
Kc = Jc * ((height)/(Nb_Slice));
Btot = [0 0 0];
Surface_Centre = Pyramid_Base;
topdim(1) = Pyramid_Dimension(1)*(1-((2*height)/(3*Pyramid_Dimension(abs(Caxis)))));
topdim(2) = Pyramid_Dimension(2)*(1-((2*height)/(3*Pyramid_Dimension(abs(Caxis)))));
topdim(3) = Pyramid_Dimension(3)*(1-((2*height)/(3*Pyramid_Dimension(abs(Caxis)))));
for i = 1 : Nb_Slice
   Surface_Centre(abs(Caxis)) = Pyramid_Base(abs(Caxis))+...
                                i*sign(Caxis)*(height/(Nb_Slice+1));
   Surface_Dimensiontemp = Pyramid_Dimension.*...
                           (1- (topdim./Pyramid_Dimension)*(i/(Nb_Slice+1)));  
   if(Flagonlyonedir==1)
       Surface_Dimensiontemp(1) = Pyramid_Dimension(1);
   elseif(Flagonlyonedir==2)
       Surface_Dimensiontemp(2) = Pyramid_Dimension(2);
   end
   Surface_Dimensiontemp(abs(Caxis)) = 0;
   Btot = Btot + B_1Supercond_Surface(abs(Caxis), Surface_Centre,...
          Surface_Dimensiontemp, P, Kc, Nb_Spire);   
   %% DEBUG Verify the created shape
%    x1 = Surface_Centre(1) - Surface_Dimensiontemp(1)/2;
%    x2 = Surface_Centre(1) + Surface_Dimensiontemp(1)/2;
%    
%    y1 = Surface_Centre(2) - Surface_Dimensiontemp(2)/2;
%    y2 = Surface_Centre(2) + Surface_Dimensiontemp(2)/2;
%    
%    z1 = Surface_Centre(3) - Surface_Dimensiontemp(3)/2;
%    z2 = Surface_Centre(3) + Surface_Dimensiontemp(3)/2; 
%    
%    
%    plot3([x1 x2],[y1 y1],[z1 z2],'b')
%    hold on;
%    plot3([x1 x2],[y2 y2],[z1 z2],'b')
%    plot3([x1 x1],[y1 y2],[z1 z2],'b')
%    plot3([x2 x2],[y1 y2],[z1 z2],'b')
%    
%    plot3([x1 x2],[y1 y2],[z1 z1],'b')
%    plot3([x1 x2],[y1 y2],[z2 z2],'b')
%    plot3([x1 x1],[y1 y2],[z1 z2],'b')
%    plot3([x2 x2],[y1 y2],[z1 z2],'b')
%    
%    plot3([x1 x2],[y1 y2],[z1 z1],'b')
%    plot3([x1 x2],[y1 y2],[z2 z2],'b')
%    plot3([x1 x2],[y1 y1],[z1 z2],'b')
%    plot3([x1 x2],[y2 y2],[z1 z2],'b')
%    xlabel('x')
%    ylabel('y')
%    zlabel('z')

   
end
end