%% This script lauch a serie of Simulation to simulate Mh Loops
%% Chose Temperature to consider 
Temperature = 65;

% Applied field
bmin_m = [50 100 150 200 300 400 500]*0.001;
bmax_m = bmin_m;
nbSudyval = length(bmin_m);

% Geometry --> don't change
ax = ones(1,nbSudyval)*0.006;
ay = ones(1,nbSudyval)*0.006;
az = ones(1,nbSudyval)*0.006;

% Law jcB 
Flag_JcB = 0; % 0 : indep of B, 1 : Kim, 2: extended Kim
FittedJcBLaw;
bmax_m = bmin_m;

% Computing
f = waitbar(0,'Computing');
for i = 1:nbSudyval
    waitbar(i/nbSudyval, f, sprintf('Solving case background field at %g K %g/%g',Temperature,i,nbSudyval));
    % Save directory 
    Str_SaveDir = strcat('D:\Michel\CuboidSuperConductorsWP1\Rotating\BatchRotation\JcConst\FC\Batch',...
                         sprintf('%gKFrom0mTTo%gmT',Temperature,bmin_m(end)*1000),...
                         '\',sprintf('Background%g',bmin_m(i)*1000),'\');
    mkdir(Str_SaveDir)

    system([strcat('gmsh Cuboid_Superconductors.geo',...
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m(i)),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m(i)),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]);
    copyfile('Cuboid_Superconductors.msh', Str_SaveDir);
    mkdir(strcat(Str_SaveDir,'res\'));
    
    system([strcat('getdp Cuboid_Superconductors.pro -solve MagDyn',...
                   ' -name ', sprintf(' %s',Str_SaveDir),'Cuboid_Superconductors',... 
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -pos MagDyn -verbose 3',... 
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m(i)),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m(i)),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]); 

    fid = fopen(strcat(Str_SaveDir,'Param.txt'),'w');
    fprintf(fid,'%g %g %g %g %g %g %g %g %g %g %g %g',...
                ax(i),ay(i),az(i),Flag_JcB,...
                jc0_1(i),n1_1(i),B0_1(i),...
                aFE_1(i),B1FE_1(i),B2FE_1(i),...
                bmax_m(i),bmin_m(i));
    fclose(fid)
end    
