%% This script lauch a serie of Simulation to simulate Mh Loops
%% Param to study
nbSudyval = 4;
% Geometry
ax = ones(1,nbSudyval)*0.00154;
ay = ones(1,nbSudyval)*0.00175;
az = ones(1,nbSudyval)*0.00503;

% Applied field 
bmax_m = [4 5 6 7];
bmin_m = -bmax_m;

% Law jcB
Flag_JcB = 2;
jc_1  = [9.92104 10.8085 13.7039 19.3299]*1e8;
n_1   = ones(1,nbSudyval)*20;
jc0_1 = jc_1;
n1_1  = ones(1,nbSudyval)*20;
n0_1  = n1_1;
B0_1    = [0.125829 0.24934 0.306926 0.274045];

aFE_1    = [7.97279 17.6562 35.1051 94.3455];
B1FE_1    = [15.1312 12.4687 13.0254 17.3794];
B2FE_1    = [9.95767 9.92377 11.1213 16.7355];

% Computing
f = waitbar(0,'Computing');
for i = 1:nbSudyval
    waitbar(i/nbSudyval, f, sprintf('Solving Case %g/%g', i, nbSudyval));
    % Save directory 
    Str_SaveDir = strcat('res\For_Matlab\ResultsFittedFEFINAL\',...
                         sprintf('bmax_m%g',bmax_m(i)),...
                         sprintf('bmin_m%g',bmin_m(i)),...
                         sprintf('az%g',az(i)),...
                         sprintf('Flag_JcB%g',Flag_JcB),...               
                         sprintf('jc_1%g',round((jc_1(i)/1e6))/100),...
                         sprintf('n_1%g',n_1(i)),...           
                         sprintf('jc0_1%g', round((jc0_1(i)/1e6))/100),...
                         sprintf('n1_1%g',n1_1(i)),...
                         sprintf('n0_1%g',n0_1(i)),...
                         sprintf('B0_1%g',B0_1(i)),...
                         sprintf('aFE%g',aFE_1(i)),...
                         sprintf('B1FE%g',B1FE_1(i)),...
                         sprintf('B2FE%g',B2FE_1(i)),'\');
    mkdir(Str_SaveDir)

    system([strcat('gmsh Cuboid_Superconductors.geo',...
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -setnumber', sprintf(' ax %g',ax(i)),...
                   ' -setnumber', sprintf(' ay %g',ay(i)),...
                   ' -setnumber', sprintf(' az %g',az(i)),...
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m(i)),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m(i)),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]);

    system([strcat('getdp Cuboid_Superconductors.pro -solve MagDyn',...
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -pos MagDyn -verbose 3',... 
                   ' -setnumber', sprintf(' ax %g',ax(i)),...
                   ' -setnumber', sprintf(' ay %g',ay(i)),...
                   ' -setnumber', sprintf(' az %g',az(i)),...
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m(i)),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m(i)),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]); 

    movefile ('Cuboid_Superconductors.res', Str_SaveDir);
    fid = fopen(strcat(Str_SaveDir,'Param.txt'),'w');
    fprintf(fid,'%g %g %g %g %g %g %g %g %g %g',...
                ax(i),ay(i),az(i),Flag_JcB,...
                jc0_1(i),n1_1(i),B0_1(i),...
                aFE_1(i),B1FE_1(i),B2FE_1(i));
    fclose(fid)
end    
