%% This script lauch a serie of Simulation to simulate Mh Loops
%% Param to study
nbSudyval = 1;
% Geometry
ax = ones(1,nbSudyval)*0.00154;
ay = ones(1,nbSudyval)*0.00175;
az = ones(1,nbSudyval)*0.00503;

% Applied field 
bmax_m = 3;
bmin_m = -3;

% Law jcB
Flag_JcB = 2;
jc_1  = ones(1,nbSudyval)*9.615*1e8;
n_1   = ones(1,nbSudyval)*20;
jc0_1 = ones(1,nbSudyval)*9.615*1e8;
n1_1  = ones(1,nbSudyval)*20;
n0_1  = n1_1;
B0_1    = ones(1,nbSudyval)*0.135571;

aFE_1    = ones(1,nbSudyval)*6.22529;
B1FE_1    = ones(1,nbSudyval)*14.2954;
B2FE_1    = ones(1,nbSudyval)*8.77606;

% Computing
f = waitbar(0,'Computing');
for i = 1:nbSudyval
    waitbar(i/nbSudyval, f, sprintf('Solving az %g/2', az(i)));
    % Save directory 
    Str_SaveDir = strcat('res\For_Matlab\ResultsTryFE\',...
                         sprintf('bmax_m%g',bmax_m),...
                         sprintf('bmin_m%g',bmin_m),...
                         sprintf('az%g',az(i)),...
                         sprintf('Flag_JcB%g',Flag_JcB),...               
                         sprintf('jc_1%g',round((jc_1(i)/1e6))/100),...
                         sprintf('n_1%g',n_1(i)),...           
                         sprintf('jc0_1%g', round((jc0_1(i)/1e6))/100),...
                         sprintf('n1_1%g',n1_1(i)),...
                         sprintf('n0_1%g',n0_1(i)),...
                         sprintf('B0_1%g',B0_1(i)),...
                         sprintf('aFE%g',aFE_1(i)),...
                         sprintf('B1FE%g',B1FE_1(i)),...
                         sprintf('B2FE%g',B2FE_1(i)),'\');
    mkdir(Str_SaveDir)

    system([strcat('gmsh Cuboid_Superconductors.geo',...
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -setnumber', sprintf(' ax %g',ax(i)),...
                   ' -setnumber', sprintf(' ay %g',ay(i)),...
                   ' -setnumber', sprintf(' az %g',az(i)),...
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]);

    system([strcat('getdp Cuboid_Superconductors.pro -solve MagDyn',...
                   ' -setstring', sprintf(' Str_SaveDir %s',Str_SaveDir),...
                   ' -pos MagDyn -verbose 3',... 
                   ' -setnumber', sprintf(' ax %g',ax(i)),...
                   ' -setnumber', sprintf(' ay %g',ay(i)),...
                   ' -setnumber', sprintf(' az %g',az(i)),...
                   ' -setnumber', sprintf(' bmax_m %g',bmax_m),...
                   ' -setnumber', sprintf(' bmin_m %g',bmin_m),...
                   ' -setnumber', sprintf(' Flag_JcB %g',Flag_JcB),...               
                   ' -setnumber', sprintf(' jc_1 %g',jc_1(i)),...
                   ' -setnumber', sprintf(' n_1 %g',n_1(i)),...           
                   ' -setnumber', sprintf(' jc0_1 %g',jc0_1(i)),...
                   ' -setnumber', sprintf(' n1_1 %g',n1_1(i)),...
                   ' -setnumber', sprintf(' n0_1 %g',n0_1(i)),...
                   ' -setnumber', sprintf(' B0_1 %g',B0_1(i)),...
                   ' -setnumber', sprintf(' aFE_1 %g',aFE_1(i)),...
                   ' -setnumber', sprintf(' B1FE_1 %g',B1FE_1(i)),...
                   ' -setnumber', sprintf(' B2FE_1 %g',B2FE_1(i)),...
                   ' -3') ]); 

    movefile ('Cuboid_Superconductors.res', Str_SaveDir);
    fid = fopen(strcat(Str_SaveDir,'Param.txt'),'w');
    fprintf(fid,'%g %g %g %g %g %g %g %g %g %g',...
                ax(i),ay(i),az(i),Flag_JcB,...
                jc0_1(i),n1_1(i),B0_1(i),...
                aFE_1(i),B1FE_1(i),B2FE_1(i));
    fclose(fid)
end    
